import { NextResponse } from 'next/server';
import { sanitizeInputText } from '@/lib/security';

export const dynamic = 'force-dynamic';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { centerName, topic, activities, challenges, studentCount, volunteerCount } = body;

    // Sanitize user inputs to prevent prompt injection and XSS
    const cleanCenterName = sanitizeInputText(centerName, 100) || 'Vihana Center';
    const cleanTopic = sanitizeInputText(topic, 200) || 'Mathematics & Literacy';
    const cleanActivities = sanitizeInputText(activities, 500) || 'Interactive group learning and 1-on-1 mentoring sessions.';
    const cleanChallenges = sanitizeInputText(challenges, 500) || 'Follow-up targeted tutoring recommended for foundational steps.';

    // Generate structured impact summary
    const summary = `
📌 **Executive Impact Report - ${cleanCenterName}**

• **Educational Focus:** ${cleanTopic}
• **Field Execution:** ${cleanActivities}
• **Operational Metrics:** ${Number(volunteerCount) || 10} active volunteers managed a cohort of ${Number(studentCount) || 45} students.
• **Challenges & Interventions:** ${cleanChallenges}

*Generated by Volunteer OS AI Copilot*
    `.trim();

    return NextResponse.json({ summary });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
